### ISSUE TITLE
Provide .jar package.

### ISSUE THREAD

**Issue by arichiardi** [timroes/EnhancedListView#22]
Hello Tim,

I would like to ask you if you can upload a simple jar package in your maven repository (instead of aar).

I tried to import EnhancedListView in Eclipse (my m2e plugin is the latest 1.5.0 snapshot) but there is a pending feature request for ADT for correctly handling .aar dependencies and it didn't work (see rgladwell/m2e-android#177 for details).

By the way, the current correct Maven import is (note type):

```
<dependency>
    <groupId>de.timroes.android</groupId>
    <artifactId>EnhancedListView</artifactId>
    <version>0.1.3</version>
    <type>aar</type>
</dependency>
```

But as I said, the compilation phase fails.

Ps: thank you for the other answer.

**Comment by timroes** [comment]
Short answer: Sorry, no.

A bit longer answer: I can't, because the project requires resources and other Android stuff, that doesn't fit in a JAR. In the (not official) old android-plugin for maven, you could produce some kind of jar library afaik (never used it) and use the same plugin to include such android pseudo jar libraries in your project. But I am using Gradle to build the project and not maven (or the maven-android-plugin). Gradle does not support the (never officially supported or defined) old jar format of that 3rd part plugin. So I cannot build a jar from the project. If you need to stuck with the old build system (don't know if eclipse has a Gradle support, neither use it) I fear there is no other way than including the source code of the library (either directly into your project or do an old build system library project for it).

**Comment by colemarkham** [comment]
I have the same situation (except not using maven), and I had to import as a project into Eclipse and rework some things to get the project structure right for ADT. I will try to fork and post my changes; you would also have to import as a project in your Eclipse. Hopefully they will get ADT updated soon as promised.
