### ISSUE TITLE
Android Studio doesn't show import properly

### ISSUE THREAD

**Issue by saadfarooq** [timroes/EnhancedListView#24]
Android Studio 0.4.0 isn't able to "show"  the import properly i.e. the actual import works fine. The project builds and runs fine. It's just that AS can't find it. This is probably an AS issue but I think you'd be a better person to raise the issue if that is the case. 

![image](https://f.cloud.github.com/assets/824816/1946271/be615e3a-7ff6-11e3-90ad-ac1a87fa687e.png)

**Comment by timroes** [comment]
Hi, this is definately an AS/Gradle issue. Have you tried: 

(a) Pressing the 'Sync Project with Gradle files' button in the toolbar (or unter `Tools->Android`). Most of the time it won't detect a new dependency without clicking this. 
(b) Try to restart Android Studio, it might help sometimes. 
(c) [I never needed this to have a new dependency detected] `Files->Invalidate Caches / Restart`

Please drop me some feedback if that helped you. If not, I think you should open a bug issue, since it doesn't matter who opened the issue, and its better the one opened it, who can reproduce that (and might answer potential questions).

**Comment by saadfarooq** [comment]
I removed all the configuration folder and iml files and re-imported the project and that seemed to work. Closing this now.
